# a Courtesy of Respect/Foundation

language: php

php:
  - 5.3
  - 5.4

before_script:
  - make foundation-develop
  - make composer-install

script:
  - make test

notifications:
  irc:
    channels:
      - "irc.freenode.org#php-respect"
    use_notice: true
